version: "3.8"

# Ports
# host:container

services:
  admin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: ulala-phpadmin
    networks:
      - database
    depends_on:
      - db
    ports:
      - "8081:80"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      PMA_HOST: ${MYSQL_HOST}
      PMA_PORT: ${MYSQL_PORT}

  db:
    container_name: db
    image: mysql/mysql-server:latest
    restart: on-failure
    networks:
      - database
    volumes:
      - "dbdata2:/var/lib/mysql"
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    environment:
      MYSQL_TCP_PORT: ${MYSQL_PORT}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: backend
      MYSQL_USER: ulala
      MYSQL_PASSWORD: ulala
      MYSQL_ROOT_HOST: "%"

  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: always
    container_name: api
    networks:
      - webapp
      - database
    depends_on:
      - db
    ports:
      - "${NEST_PORT}:${NEST_PORT}"
    expose:
      - "${NEST_PORT}"
    command: 'yarn run start:prod'
    #    command: ['./wait-for-it.sh', 'db:${MYSQL_PORT}', '--', 'node', 'main.js']
    env_file: .env

  client:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - webapp
    ports:
      - 80:80
    depends_on:
      - api
    restart: always

networks:
  webapp:
    driver: bridge
  database:
    driver: bridge

volumes:
  dbdata2:
