FROM node:lts-alpine
WORKDIR /var/server

COPY . .

RUN ["npm", "install", "-g", "nodemon", "--silent"]
RUN ["npm", "install", "-g", "@nestjs/cli"]
RUN ["apk", "add", "--no-cache", "bash"]

RUN ["yarn"]
RUN ["yarn", "start:dev"]

EXPOSE 5500
